# ----------------------- #
#      Main Configs       #
# ----------------------- #
root: /
url: http://likemenuiserie.com
title: LIKE MENUISERIE
email: contact@likemenuiserie.com
author: Airilight web development
description: > # "Write an awesome description for your new site here.
  Like menuiseries, est une entreprise Bordelaise localisé dans la ville de Cenon.
  Nous sommes spécialisé dans la vente, la pose, et l’installation de menuiserie
  en PVC, bois, ou alu. Nous délivrons nos services sur du neuf, comme sur de la
  rénovation, sur Bordeaux Métropole et l'ensemble du département de la Gironde.
copyright: 'Copyright &copy; 2019 Like Menuiserie. All Rights Reserved.'
credits: 'LIKE MENUISERIE:<br> Centre Emeraude - 61-69 Rue Camille Pelletan<br> Cidex 30 - 33150 Cenon <a href="/contact" style="color: #428bca;">05 24 84 14 00</a>.'
# baseurl: "/likemenuiserie-beta"
# url: http://IsmaelSANE.github.io
# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: facebook
    url: https://www.facebook.com/likemenuiserie/
  - title: linkedin
    url:
  - title: instagram
    url:
